// Code generated by mockery v2.36.0. DO NOT EDIT.

package service

import (
	model "github.com/CS20-SIT/Graduation-Bot/media-uploader/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// UploadContent provides a mock function with given fields: msg
func (_m *MockService) UploadContent(msg model.UploadContentMessage) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.UploadContentMessage) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UploadContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadContent'
type MockService_UploadContent_Call struct {
	*mock.Call
}

// UploadContent is a helper method to define mock.On call
//   - msg model.UploadContentMessage
func (_e *MockService_Expecter) UploadContent(msg interface{}) *MockService_UploadContent_Call {
	return &MockService_UploadContent_Call{Call: _e.mock.On("UploadContent", msg)}
}

func (_c *MockService_UploadContent_Call) Run(run func(msg model.UploadContentMessage)) *MockService_UploadContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.UploadContentMessage))
	})
	return _c
}

func (_c *MockService_UploadContent_Call) Return(_a0 error) *MockService_UploadContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UploadContent_Call) RunAndReturn(run func(model.UploadContentMessage) error) *MockService_UploadContent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
